export const dailyVideoData = {
  issue: "001",
  dateLabel: "2026.06.02",
  dateChinese: "2026年6月2日",
  weekday: "星期二",
  captureTime: "11:16 CST",
  siteUrl: "github-daily.xiajuan.app",
  stats: {
    trending: 16,
    deduped: 46,
    ai: 8,
    trading: 8,
    crossListed: 2,
  },
  topRepos: [
    {
      rank: 1,
      fullName: "microsoft/markitdown",
      label: "文档转 Markdown",
      language: "Python",
      starsToday: 3034,
      totalStars: "138.8k",
      summary: "把 Office、PDF、网页等资料转为 Markdown，让 Agent 和知识库更快吃进真实文件。",
    },
    {
      rank: 2,
      fullName: "nesquena/hermes-webui",
      label: "Agent Web UI",
      language: "Python",
      starsToday: 945,
      totalStars: "11.5k",
      summary: "把 Hermes Agent 放进浏览器和手机端，Agent 产品开始从命令行走向日常界面。",
    },
    {
      rank: 3,
      fullName: "supermemoryai/supermemory",
      label: "AI 时代记忆引擎",
      language: "TypeScript",
      starsToday: 647,
      totalStars: "24.1k",
      summary: "面向 AI 应用的长期记忆 API，今天继续验证“可检索记忆”是应用层刚需。",
    },
  ],
  aiWatch: [
    ["AutoGPT", "184.7k"],
    ["prompts.chat", "163.2k"],
    ["LLMs-from-scratch", "96.5k"],
    ["claude-mem", "80.1k"],
  ],
  tradingWatch: [
    ["TradingAgents", "81.9k"],
    ["freqtrade", "51.0k"],
    ["microsoft/qlib", "43.9k"],
    ["ccxt", "42.8k"],
  ],
  insights: [
    "AI 热点正在从模型本身转向资料处理、记忆、Agent UI 和工作流落地。",
    "交易赛道出现明显 LLM 化：多智能体、量化研究与自动化执行开始同屏竞争。",
    "去重后 46 个项目进入日报，适合用一页纸完成筛选，再点击仓库深入查看。",
  ],
};
