export const dailyVideoData = {
  issue: "002",
  dateLabel: "2026.06.03",
  dateChinese: "2026年6月3日",
  weekday: "星期三",
  captureTime: "16:23 CST",
  siteUrl: "github-daily.xiajuan.app",
  stats: {
    trending: 11,
    deduped: 42,
    ai: 8,
    trading: 8,
    crossListed: 1,
  },
  topRepos: [
    {
      rank: 1,
      fullName: "chopratejas/headroom",
      label: "LLM 输入压缩器",
      language: "Python",
      starsToday: 1265,
      totalStars: "7.6k",
      summary: "把日志、文件和 RAG 分块先压缩再喂给模型，直接围绕 token 成本和上下文效率做优化。",
    },
    {
      rank: 2,
      fullName: "microsoft/markitdown",
      label: "文档转 Markdown",
      language: "Python",
      starsToday: 3618,
      totalStars: "141.9k",
      summary: "把 Office、PDF、网页等资料转为 Markdown，继续稳居 AI 工作流入口型工具前排。",
    },
    {
      rank: 3,
      fullName: "affaan-m/ECC",
      label: "Agent Harness 优化",
      language: "JavaScript",
      starsToday: 1533,
      totalStars: "204.6k",
      summary: "围绕 Claude Code、Codex、Cursor 的技能、记忆和研究流程做系统化提效，说明开发工具链仍在高速重组。",
    },
  ],
  aiWatch: [
    ["AutoGPT", "184.7k"],
    ["prompts.chat", "163.2k"],
    ["LLMs-from-scratch", "96.6k"],
    ["Deep-Live-Cam", "93.6k"],
  ],
  tradingWatch: [
    ["TradingAgents", "82.5k"],
    ["ccxt", "42.8k"],
    ["vnpy", "41.3k"],
    ["FinceptTerminal", "25.1k"],
  ],
  insights: [
    "AI 热点继续围绕上下文处理、输入压缩和资料入库，工程化效率工具更容易冲上前排。",
    "开发者工具链开始竞争 agent harness 与工作流控制面，说明“怎么更好地用模型”本身就是热点。",
    "去重后 42 个项目进入日报，适合先用一页纸完成筛选，再深入点开仓库验证价值。",
  ],
};
